# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-17 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_mainnustbuy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainNustBuy',
            new_name='MainMustBuy',
        ),
    ]
